# Generated by Django 5.2.3 on 2025-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date de création de la ressource",
                verbose_name="Date de création",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description de la ressource",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si la ressource est active (visible sur le site)",
                verbose_name="Actif",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="name",
            field=models.CharField(
                help_text="Nom de la ressource", max_length=255, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date de mise à jour de la ressource",
                verbose_name="Date de mise à jour",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(
                help_text="URL de la ressource", max_length=255, verbose_name="URL"
            ),
        ),
    ]
