# Generated by Django 5.2.3 on 2025-06-16 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventsubscription",
            options={
                "ordering": ["event", "user"],
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
            },
        ),
    ]
