apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ft-frontend
  namespace: {{ .Release.Namespace }}
spec:
  host: ft-frontend
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ft-postgres
  namespace: {{ .Release.Namespace }}
spec:
  host: ft-postgres
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-rule
  namespace: {{ .Release.Namespace }}
spec:
  host: ft-backend
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
      sni: ft-backend.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
