# Generated by Django 5.2.3 on 2025-06-18 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Date de début de l'adhésion",
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Date de fin de l'adhésion",
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si l'événement est actif (visible sur le site)",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de l'adhésion",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de mise à jour de l'adhésion",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhésion",
                "verbose_name_plural": "Adhésions",
                "ordering": ["start_date", "end_date"],
            },
        ),
    ]
