# Generated by Django 5.2.3 on 2025-06-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="at_compiegne",
            field=models.BooleanField(
                default=True,
                help_text="Si l'événement est à Compiegne",
                verbose_name="À Compiegne",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Si l'événement est public",
                verbose_name="Public",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="url_signup",
            field=models.URLField(
                blank=True,
                help_text="URL de l'inscription à l'événement",
                max_length=255,
                null=True,
                verbose_name="URL de l'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="url_website",
            field=models.URLField(
                blank=True,
                help_text="URL du site web de l'événement",
                max_length=255,
                null=True,
                verbose_name="URL du site web",
            ),
        ),
    ]
