# Generated by Django 5.2.3 on 2025-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_at_compiegne_event_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONGRESS", "Congrès"),
                    ("DRINK", "Apéral"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                help_text="Type de l'événement",
                max_length=255,
                verbose_name="Type",
            ),
            preserve_default=False,
        ),
    ]
