# Generated by Django 5.2.3 on 2025-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONGRESS", "Congrès"),
                    ("DRINK", "Apéral"),
                    ("OFFICE", "Office"),
                    ("OTHER", "Autre"),
                ],
                help_text="Type de l'événement",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
