# Generated by Django 5.2.3 on 2025-06-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsubscription",
            name="can_invite",
        ),
        migrations.RemoveField(
            model_name="eventsubscription",
            name="is_active",
        ),
        migrations.AddField(
            model_name="eventsubscription",
            name="answer",
            field=models.CharField(
                choices=[
                    ("YES", "Participe"),
                    ("NO", "Ne paricipe pas"),
                    ("MAYBE", "Peut-Être"),
                ],
                default="MAYBE",
                help_text="Réponse de l'utilisateur",
                max_length=6,
                verbose_name="Réponse",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("CONGRESS", "Congrès"),
                    ("DRINK", "Apéral"),
                    ("OFFICE", "Office"),
                    ("OTHER", "Autre"),
                ],
                help_text="Type de l'événement",
                max_length=8,
                verbose_name="Type",
            ),
        ),
    ]
