# Generated by Django 5.2.3 on 2025-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_remove_eventsubscription_can_invite_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_date", "name"],
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
            },
        ),
    ]
