# Generated by Django 5.2.3 on 2025-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubscription",
            name="can_invite",
            field=models.BooleanField(
                default=False,
                help_text="Si l'utilisateur peut inviter d'autres utilisateurs",
                verbose_name="Peut inviter",
            ),
        ),
    ]
