# Generated by Django 5.2.3 on 2025-06-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_eventsubscription_can_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubscription",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si l'inscription est active (debug only)",
                verbose_name="Actif",
            ),
        ),
    ]
