# Generated by Django 5.2.3 on 2025-07-02 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_eventsubscription_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_beds",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre de lits disponibles pour les personnes hébergées",
                        verbose_name="Nombre de lits disponibles",
                    ),
                ),
                (
                    "custom_rules",
                    models.TextField(
                        blank=True,
                        help_text="Règles spécifiques pour cet hébergement (si différentes des règles habituelles)",
                        null=True,
                        verbose_name="Règles spécifiques",
                    ),
                ),
                (
                    "address_override",
                    models.CharField(
                        blank=True,
                        help_text="Adresse spécifique pour cet hébergement (si différente de l'adresse habituelle)",
                        max_length=200,
                        null=True,
                        verbose_name="Adresse spécifique",
                    ),
                ),
                (
                    "city_override",
                    models.CharField(
                        blank=True,
                        help_text="Ville spécifique pour cet hébergement (si différente de la ville habituelle)",
                        max_length=100,
                        null=True,
                        verbose_name="Ville spécifique",
                    ),
                ),
                (
                    "zip_code_override",
                    models.CharField(
                        blank=True,
                        help_text="Code postal spécifique pour cet hébergement (si différent du code postal habituel)",
                        max_length=10,
                        null=True,
                        verbose_name="Code postal spécifique",
                    ),
                ),
                (
                    "country_override",
                    models.CharField(
                        blank=True,
                        help_text="Pays spécifique pour cet hébergement (si différent du pays habituel)",
                        max_length=100,
                        null=True,
                        verbose_name="Pays spécifique",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si l'offre d'hébergement est active",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de l'offre d'hébergement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de mise à jour de l'offre d'hébergement",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Événement pour lequel l'hébergement est proposé",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        help_text="Utilisateur qui propose l'hébergement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_hostings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hôte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hébergement",
                "verbose_name_plural": "Hébergements",
                "ordering": ["event", "host"],
                "unique_together": {("event", "host")},
            },
        ),
        migrations.CreateModel(
            name="EventHostingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        help_text="Statut de la demande d'hébergement",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message du demandeur à l'hôte",
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "host_message",
                    models.TextField(
                        blank=True,
                        help_text="Message de l'hôte au demandeur",
                        null=True,
                        verbose_name="Message de l'hôte",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de la demande",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de mise à jour de la demande",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "hosting",
                    models.ForeignKey(
                        help_text="Hébergement demandé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="event.eventhosting",
                        verbose_name="Hébergement",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="Utilisateur qui fait la demande d'hébergement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosting_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'hébergement",
                "verbose_name_plural": "Demandes d'hébergement",
                "ordering": ["-created_at"],
                "unique_together": {("hosting", "requester")},
            },
        ),
    ]
