# Generated by Django 5.1.6 on 2025-07-07 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_eventhosting_eventhostingrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpoolTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_city",
                    models.CharField(
                        help_text="Ville de départ du trajet",
                        max_length=255,
                        verbose_name="Ville de départ",
                    ),
                ),
                (
                    "departure_address",
                    models.CharField(
                        blank=True,
                        help_text="Adresse précise du lieu de départ",
                        max_length=255,
                        null=True,
                        verbose_name="Adresse de départ",
                    ),
                ),
                (
                    "arrival_city",
                    models.CharField(
                        help_text="Ville d'arrivée du trajet",
                        max_length=255,
                        verbose_name="Ville d'arrivée",
                    ),
                ),
                (
                    "arrival_address",
                    models.CharField(
                        blank=True,
                        help_text="Adresse précise du lieu d'arrivée",
                        max_length=255,
                        null=True,
                        verbose_name="Adresse d'arrivée",
                    ),
                ),
                (
                    "departure_datetime",
                    models.DateTimeField(
                        help_text="Date et heure de départ du trajet",
                        verbose_name="Date et heure de départ",
                    ),
                ),
                (
                    "return_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure du trajet retour (optionnel)",
                        null=True,
                        verbose_name="Date et heure de retour",
                    ),
                ),
                (
                    "has_return",
                    models.BooleanField(
                        default=False,
                        help_text="Si un trajet retour est proposé",
                        verbose_name="Trajet retour",
                    ),
                ),
                (
                    "seats_total",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Nombre total de places disponibles",
                        verbose_name="Nombre de places",
                    ),
                ),
                (
                    "price_per_seat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Prix demandé par passager (en €)",
                        max_digits=6,
                        verbose_name="Prix par place",
                    ),
                ),
                (
                    "allow_luggage",
                    models.BooleanField(
                        default=True,
                        help_text="Si les bagages sont autorisés",
                        verbose_name="Bagages autorisés",
                    ),
                ),
                (
                    "allow_pets",
                    models.BooleanField(
                        default=False,
                        help_text="Si les animaux de compagnie sont autorisés",
                        verbose_name="Animaux autorisés",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Informations supplémentaires sur le trajet",
                        null=True,
                        verbose_name="Informations supplémentaires",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si le trajet est actif et visible",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création du trajet",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification du trajet",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Utilisateur proposant le trajet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_trips_as_driver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Conducteur",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Événement lié au trajet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_trips",
                        to="event.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet de covoiturage",
                "verbose_name_plural": "Trajets de covoiturage",
                "ordering": ["departure_datetime", "event"],
            },
        ),
        migrations.CreateModel(
            name="CarpoolRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        help_text="Statut de la demande",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "seats_requested",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Nombre de places demandées",
                        verbose_name="Places demandées",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message à l'attention du conducteur",
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        help_text="Réponse du conducteur",
                        null=True,
                        verbose_name="Réponse",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si la demande est active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de la demande",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification de la demande",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        help_text="Utilisateur demandant une place",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carpool_requests_as_passenger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Passager",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trajet concerné par la demande",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="event.carpooltrip",
                        verbose_name="Trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de covoiturage",
                "verbose_name_plural": "Demandes de covoiturage",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("passenger", "trip"), name="unique_passenger_trip"
                    )
                ],
            },
        ),
    ]
