# Generated by Django 5.1.6 on 2025-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_carpooltrip_carpoolrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpoolrequest",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="Si le passager a remboursé le conducteur pour le trajet",
                verbose_name="Payée",
            ),
        ),
        migrations.AddField(
            model_name="carpoolrequest",
            name="payment_notes",
            field=models.CharField(
                blank=True,
                help_text="Informations complémentaires sur le paiement",
                max_length=255,
                null=True,
                verbose_name="Notes de paiement",
            ),
        ),
    ]
