# Generated by Django 5.2.4 on 2025-07-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_carpoolrequest_is_paid_carpoolrequest_payment_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpoolrequest",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="carpoolrequest",
            name="payment_notes",
        ),
        migrations.RemoveField(
            model_name="carpooltrip",
            name="allow_luggage",
        ),
        migrations.RemoveField(
            model_name="carpooltrip",
            name="allow_pets",
        ),
        migrations.AlterField(
            model_name="carpooltrip",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Événement lié au trajet",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carpool_trips",
                to="event.event",
                verbose_name="Événement",
            ),
        ),
        migrations.CreateModel(
            name="CarpoolPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du paiement (en €)",
                        max_digits=8,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le paiement est complet",
                        verbose_name="Paiement complet",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("TRANSFER", "Virement bancaire"),
                            ("MOBILE", "Paiement mobile"),
                            ("OTHER", "Autre"),
                        ],
                        default="CASH",
                        help_text="Méthode utilisée pour le paiement",
                        max_length=10,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Informations complémentaires sur le paiement",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création du paiement",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification du paiement",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="Demande de covoiturage concernée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="event.carpoolrequest",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement de covoiturage",
                "verbose_name_plural": "Paiements de covoiturage",
                "ordering": ["-created_at"],
            },
        ),
    ]
