# Generated by Django 5.1.6 on 2025-07-13 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_remove_carpoolrequest_is_paid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carpoolrequest",
            name="unique_passenger_trip",
        ),
        migrations.AddConstraint(
            model_name="carpoolrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "ACCEPTED"])),
                fields=("passenger", "trip", "status"),
                name="unique_passenger_trip_active",
            ),
        ),
    ]
